version: '3.7'
services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=digital-farm
    ports:
      - "5432:5432"
    volumes:
      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql

  pgadmin-compose:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "postgres@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "postgres!"
    ports:
      - "16544:80"
    depends_on:
      - postgres
  #SpringBoot APP
  digital-farm:
    build: .
    image: digital-farm
    container_name: digital-farm
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/digital-farm
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - postgres
    links:
      - postgres